#!/bin/bash

#create kubernetes bigip container connecter w/ nodeport, authentication and RBAC
oc create secret generic bigip-login -n kube-system --from-literal=username=admin --from-literal=password=bigip123
oc create serviceaccount bigip-ctlr -n kube-system
oc create -f f5-kctlr-openshift-clusterrole.yaml
oc create -f f5-cluster-deployment.yaml
